version: '3.4'

services:
  app:
      build:
        context: .
        dockerfile: ./.docker/php/Dockerfile
      image: php-container
      ports:
        - 8181:80
      volumes:
        - ./app:/srv/app

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080

  web:
    build:
      context: ./web
      dockerfile: ./.docker/Dockerfile
    ports:
      - 3101:8080
